# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/newly',
                'doc_host': 'https://tuuai.github.io',
                'git_url': 'https://github.com/tuuai/newly',
                'lib_path': 'newly'},
  'syms': {'newly.core': {'newly.core.foo': ('core.html#foo', 'newly/core.py')}}}
